### ISSUE TITLE
"browser" field in package.json is not respected by Vite

### ISSUE THREAD

**Issue by joseph-ismailyan** [MeshJS/mesh#93] opened 2023-02-12 09:20 UTC
In package.json the "browser" field is not respected, so Vite runs the client side app with nodejs and throws errors. This occurs when using SvelteKit. Webpack with NextJS seems to work just fine.

https://github.com/MeshJS/mesh/blob/main/packages/module/package.json#L44-L47

EDIT: I went down the GitHub rabbit hole and found this PR that's supposed to resolve this issue but has not been merged for over a year 🙁
https://github.com/vitejs/vite/pull/11219/files

**Comment by denishacquin** [comment] 2023-02-12 21:06
I think this is a duplicate of https://github.com/MeshJS/mesh/issues/54

Would also really love a fix for this as I use vite for my projects.

**Closed** 2024-02-22 13:21 UTC
